### ISSUE TITLE
set_bom関数をを分割する

### ISSUE THREAD

**Issue by okano0120** [masaki1114/mainsweeper#1]
https://github.com/masaki1114/mainsweeper/blob/f9b20d4e9e3ae81eaf501c8168058a4122754bfe/mainsweeper.py#L172-L210

set_bom関数には、機能がたくさんあるため1関数に1機能にしていく（長いから分けれるところを自分で考えて分けてみてください）。

**Comment by kawasakitakuma** [comment]
@okano0120
確認よろしくお願いします！

**Comment by okano0120** [comment]
他のやつはCloseしているので、一旦このタイミングでClose
