### ISSUE TITLE
click関数を分割する

### ISSUE THREAD

**Issue by kawasakitakuma** [masaki1114/mainsweeper#2]
https://github.com/masaki1114/mainsweeper/blob/f9b20d4e9e3ae81eaf501c8168058a4122754bfe/mainsweeper.py#L86-L120

click関数もコードが多いため分割していく。

**Comment by kawasakitakuma** [comment]
@okano0120
closeしました！
確認よろしくお願いします！

**Comment by okano0120** [comment]
コミット
* https://github.com/masaki1114/mainsweeper/commit/2265a323d8c8dba6b58a3696bb2daaa25a0013dc
