### ISSUE TITLE
関数名を変更

### ISSUE THREAD

**Issue by kawasakitakuma** [masaki1114/mainsweeper#4]
https://github.com/masaki1114/mainsweeper/blob/39d20980400f4d27b9d88a4975cd793b57a46fba/mainsweeper.py#L162

修正確認しました！
動作もコードも共に素晴らしいと思いました！

関数名が大幅に違うな（僕も関数を名付けるのよく苦戦してます）と思ったのが、around_clickです。

_周りをクリックする_だと、やっていることとコードで記載されていることとで違うので、修正していただきたいです！

**Comment by kawasakitakuma** [comment]
@okano0120
closeしました！
確認よろしくお願いします！

**Comment by okano0120** [comment]
コミット
* https://github.com/masaki1114/mainsweeper/commit/7f28b50e22cfb73190c74683732bdd07782d5fba
