### ISSUE TITLE
Runtimeerror解消

### ISSUE THREAD

**Issue by kawasakitakuma** [masaki1114/mainsweeper#5]
`congratulation!!`が出た際に、他のマスをクリックすると`RuntimeError: can't re-enter readline`（下記画像参照）

![image](https://user-images.githubusercontent.com/111414424/218020513-86f27817-2a09-4d7a-8ede-952eaf85146c.png)

という風になる。

ゲームオーバーの時は、他のマスをクリックしてもなにもなかったので、
ゲームクリアの時も、そのようにしてほしい。

**Comment by masaki1114** [comment]
@kawasakitakuma 
以下のリンクにて修正いたしました、確認お願いします。
（second_click_functionのif文条件の変更）
https://github.com/masaki1114/mainsweeper/blob/main/mainsweeper.py

**Comment by kawasakitakuma** [comment]
@masaki1114 
地雷のないマスはきちんと止まっています！
あとは、地雷のマス押した時は、runtimeerrorがまだ発生しているので修正してみてください！
あと少しです！

<追記>
地雷のマスは一回押したら止まっています。

**Comment by masaki1114** [comment]
@kawasakitakuma 
修正いたしました！確認お願いいたします。
https://github.com/masaki1114/mainsweeper/blob/main/mainsweeper.py

**Comment by kawasakitakuma** [comment]
@masaki1114 
素晴らしいです！Closeします！

**Comment by kawasakitakuma** [comment]
@okano0120
closeしました！
確認よろしくお願いします！
